### ISSUE TITLE
should honeybadger env setting and shared configs updating be moved up in deploy.rb?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/sdr-preservation-core#65]
currently, these things happen at the end of the deploy.rb file:
https://github.com/sul-dlss/sdr-preservation-core/blob/58a90d47d65b7b9f8507520d66fdc8cb4a9c8f63/config/deploy.rb#L57-L60

but maybe this action would benefit from having the honeybadger env and shared_configs update go first?
https://github.com/sul-dlss/sdr-preservation-core/blob/58a90d47d65b7b9f8507520d66fdc8cb4a9c8f63/config/deploy.rb#L40-L55

**Comment by darrenleeweber** [comment]
+1 to putting any and all `set` statements at the top of the deploy file for readability.  As for functional significance, I'm not sure whether the order of things is important in capistrano.  My hunch is, it's not important, cap should interpret the entire file-hierarchy and adjust all it's rules at the end.
