### ISSUE TITLE
robots: rename github repo to preservation_robot_suite

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sdr-preservation-core#76]
or prez_robot_suite or xxx_robot_suite   to be clearer about what the code is for and what it does.

May also involve:
- [ ] adjusting whenever cron jobs
- [ ] adjusting cap recipes
- [ ] adjusting puppet
- [ ] adjusting devopsdocs
- [ ] shared_configs

etc.

**Comment by darrenleeweber** [comment]
This may also entail changes to the shared_config branch names.  It's a lot of work for little gain.
👎

**Comment by ndushay** [comment]
Looks like we're going to just create a new preservation_robots repo.
